config/routes.rb
AnifagDb::Application.routes.draw do    

  devise_for :users

  root to: "static_pages#home"

  get '/search' => 'static_pages#search', as: :search

  resources :articles, except: :index
  get 'articles(/pages/:page)' => 'articles#index', as: :articles
  get 'tags/:tag(/pages/:page)' => 'tags#show', as: :tagged_with

  get 'categories/:id(/pages/:page)' => 'categories#show', as: :category

  namespace :users do
    get '/:id' => 'users#show', as: :user
  end

  mount Rich::Engine => '/rich', :as => 'rich'

end

app/models/article.rb
# coding: utf-8
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  content     :text             not null
#  title       :string(255)      not null
#  description :text             not null
#  permalink   :string(255)      not null
#  source      :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  main_image  :string(255)
#

class Article < ActiveRecord::Base
  resourcify
  include Authority::Abilities
  
  attr_accessible :content, :description, :permalink, :source, :title,
                  :tag_list, :main_image, :category_ids, :tags
  acts_as_taggable

  include Tire::Model::Search
  include Tire::Model::Callbacks

  index_name("#{Rails.env}-articles")

  belongs_to :user
  
  has_many :articles_categories, dependent: :destroy
  has_many :categories, through: :articles_categories

  validates :title, :content, :description, :permalink, presence: true
  validates :source, allow_blank: true, format: {
    with:    %r{^((http|https):\/\/)*[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?$}ix,
    message: 'не соответствует формату URL.'
  }

  before_save :sanitize_content

  default_scope order("created_at DESC")

  def to_param
    "#{id}-#{permalink}"
  end

  self.per_page = 10

  def self.search(params)
    tire.search(page: params[:page]) do
      query { string params[:query]} if params[:query].present?
      sort { by :created_at, 'desc' }
    end
  end

  tire.mapping do
    indexes :id,           :index    => :not_analyzed
    indexes :title,        :analyzer => 'snowball', :boost => 100
    indexes :content,      :analyzer => 'snowball'
    indexes :description,  :analyzer => 'snowball'
    indexes :created_at,   :type => 'date', :include_in_all => false
  end

  private
    def sanitize_content
      if self.content
        check_css = lambda do |env|
                            node      = env[:node]
                            node_name = env[:node_name]
                            # Don't continue if this node is already whitelisted or is not an element.
                            return if env[:is_whitelisted] || !node.element?
                            parent = node.parent
                            return unless node_name == 'style' || node['style']
                            if node_name == 'style'
                              unless good_css? node.content
                                node.unlink
                                return
                              end
                            else
                              unless good_css? node['style']
                                node.unlink
                                return
                              end
                            end
                            {:node_whitelist => [node]}
                          end
                          
        video_emb = lambda do |env|
                        node      = env[:node]
                        node_name = env[:node_name]
                                          
                        return if env[:is_whitelisted] || !node.element?
                                          
                        return unless node_name == 'iframe' || 
                                      node_name == 'object' || 
                                      node_name == 'param'  || 
                                      node_name == 'embed'  ||
                                      node_name == 'video'  ||
                                      node_name == 'source'
                                          
                        # return unless node['src'] =~ /\Ahttps?:\/\/(?:www\.)?(youtube(?:-nocookie)?\.com)|(ustream\.tv)|(vimeo\.com)\//
                      
                        Sanitize.clean_node!(node, {
                          :elements => %w[iframe object param embed video source],
                      
                          :attributes => {
                            'iframe'  => %w[allowfullscreen frameborder height src width webkitallowfullscreen mozallowfullscreen],
                            'object' => %w[width height],
                            'param' => %w[name value],
                            'embed' => %w[src type allowfullscreen allowScriptAccess width height],
                            'video' => %w[id class controls preload width height poster data-setup src],
                            'source' => %w[src type]
                          }
                        })

                        {:node_whitelist => [node]}
                      end
                          
        self.content = Sanitize.clean(self.content, :elements => ['p', 'blockquote', 'pre', 'h3', 'h4', 'h5', 'h6',
                                              'b', 'i', 'strike', 'ul', 'li', 'span', 'ol',
                                              'img', 'br', 'table', 'tbody', 'thead', 'tr', 
                                              'td', 'th', 'caption', 'a', 'font', 'hr', 'div'],
                                :attributes => {
                                                'a'  => ['href', 'title', 'target'],
                                                'font' => ['color'],
                                                'img' => ['border', 'height', 'src', 'width']
                                                },
                                :transformers => [check_css, video_emb])
      end    
    end
end

app/controllers/articles_controller.rb
# coding: utf-8
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  authorize_actions_for Article, except: [:index, :show]

  expose(:articles) { Article.paginate(page: params[:page]) }
  expose(:article) { params[:id] ? Article.find(params[:id]) : current_user.articles.build(params[:article]) }

  def index
  end

  def show
  end

  def new
  end

  def create
    authorize_action_for article
    if article.save
      flash[:success] = t('messages.saved')
      if params[:commit] == t('form.save_and_exit')
        redirect_to article
      else
        redirect_to edit_article_path article
      end
    else
      @errors = article.errors.full_messages
      flash[:error] = t("messages.save_error")
      render :new
    end
  end

  def edit
    authorize_action_for article
  end

  def update
    authorize_action_for article
    puts params[:article]
    if article.update_attributes(params[:article])
      flash[:success] = t('messages.saved')
      if params[:commit] == t('form.save_and_exit')
        redirect_to article
      else
        redirect_to edit_article_path article
      end
    else
      @errors = article.errors.full_messages
      flash[:error] = t("messages.save_error")
      render :edit
    end
  end

  def destroy
    authorize_action_for article
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
%h2.article-name= article.title
%article   
  .article-header 
    = render partial: 'articles/article_categories', locals: { article: article }       
    %div{ class: "article-added"}= article.created_at.strftime("%Y-%m-%d %H:%M")    
  .article-body
    - if article.main_image
      .main-image= link_to image_tag(main_image_url(article.main_image, :large)), main_image_url(article.main_image, :original)
    = article.content.html_safe
  .clearfix
  .article-footer
    = render partial: 'articles/article_tags', locals: { article: article } 
.share-buttons
  .pull-right
    %strong=t 'article.share' 
    =link_to image_tag('twitter.png'), 'http://twitter.com/share?url=' + article_url(article), target: '_blank'
    =link_to image_tag('vk.png'), 'http://vkontakte.ru/share.php?url=' + article_url(article), target: '_blank'
    =link_to image_tag('facebook.png'), 'http://www.facebook.com/sharer.php?u=' + article_url(article), target: '_blank'
    =link_to image_tag('google+.png'), 'https://plus.google.com/share?url=' + article_url(article), target: '_blank'
.comments
  %ul{class: "nav nav-tabs", id: "comments"}
    %li.active= link_to t('vk'), '#vk', 'data-toggle' => 'tab'
    %li= link_to t('dq'), '#dq', 'data-toggle' => 'tab'
  .tab-content
    %div{class: "tab-pane active", id: "vk"}
      %script{:type => "text/javascript",
              :src  => "http://userapi.com/js/api/openapi.js?52"}
      :javascript
        VK.init({apiId: SITE_ID, onlyWidgets: true});
      #vk_comments
      :javascript
        VK.Widgets.Comments("vk_comments", {limit: 15, width: "600", attach: false});
    %div{class: "tab-pane", id: "dq"}
      #disqus_thread
      :javascript
        var disqus_shortname = 'YOUR_SITE_NAME'; // required: replace example with your forum shortname
    
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
      %noscript
        Please enable JavaScript to view the
        %a{href: "http://disqus.com/?ref_noscript"} comments powered by Disqus.
      %a{href: "http://disqus.com", class: "dsq-brlink"}
        comments powered by
        %span.logo-disqus Disqus

app/views/articles/_article_categories.html.haml
%ul{ class: "inline pull-right" }
  -article.categories.each do |category|
    %li{ class: "label label-info" }= link_to category.title, category, class: "article-category"

app/views/articles/_article_description.html.haml
%article.article-description    
  .article-header 
    = render partial: 'articles/article_categories', locals: { article: article }      
    %div{ class: "article-added"}= article.created_at.strftime("%Y-%m-%d %H:%M")
    %h3= link_to article.title, article
  - if article.main_image
    .article-body
      .main-image= image_tag main_image_url(article.main_image, :large)
      %p= article.description
  - else
    .article-body= article.description.html_safe
  .article-footer
    = link_to t('article.more'), article
    = render partial: 'articles/article_tags', locals: { article: article } 

app/views/articles/_article_tags.html.haml
-if article.tag_list.any?
  .article-tags
    %strong Теги:
    %ul.inline
      -article.tag_list.each do |tag|
        %li{ class: "badge badge-info" }= link_to tag, tagged_with_path(tag), class: "article-tag"

app/views/articles/_form.html.haml
= semantic_form_for article do |f|
  .control-group
    .controls
      = f.text_field :title, placeholder: t('activerecord.attributes.article.title'), class: 'input-block-level'

  .row
    .span4
      .control-group
        = f.label :source, class: 'control-label'
      .controls
        = f.text_field :source
      .control-group
        = f.label :permalink, class: 'control-label'
      .controls
        =  f.text_field :permalink
    .span4
      .control-group
        = f.label :main_image, class: 'control-label'
      .controls
        = f.input :main_image, as: :rich_picker, config: { class: 'btn'}, label: false
      

  .control-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_area :description, rows: 8, class: 'input-block-level'

  .control-group
    = f.label :content, class: 'control-label'
    .controls
      = f.input :content, as: :rich, config: { width: '100%', height: '400px' }, label: false

  .row
    .span4      
      .control-group
        = f.label :categories, class: 'control-label'
      .controls#categories
        = select_tag :category, options_from_collection_for_select(Category.all, :id, :title), include_blank: true
        - article.category_ids.each do |id|
          = hidden_field_tag 'article[category_ids][]', id
        %ul.inline#categories-lables
          - article.categories.each do |category|
            %li
              %span.label.label-info
                = link_to '&times;'.html_safe, '#', class: 'small-close', id: category.id
                = category.title
    .span4
      .control-group
        = f.label :tags, class: 'control-label'
      .controls
        = text_field_tag :tag, nil, 'data-provide' => 'typeahead', 'data-source' => ActsAsTaggableOn::Tag.pluck(:name).to_s, autocomplete: "off"
        = hidden_field_tag 'article[tag_list]', article.tag_list.join(',')
        %ul.inline#tags-lables
          - article.tag_list.each do |tag|
            %li
              %span.label.label-info
                = link_to '&times;'.html_safe, '#', class: 'small-close', id: tag
                = tag

  .form-actions
    - if article
      = link_to "Удалить", article, method: :delete, data: { confirm: "Уверены?" }, title: "Удалить", class: "btn btn-danger pull-right"
    = f.submit t('form.save'), class: 'btn btn-success'
    = f.submit t('form.save_and_exit'), class: 'btn btn-primary'
    = link_to 'Отмена', :back, class: 'btn'

app/views/articles/edit.html.haml
%h2= t 'article.new.title'
= render 'form'

app/views/articles/index.html.haml
%h3.last-posts= t 'article.index.title'

.posts-body
  - articles.each do |article|
    = render partial: 'article_description', locals: { article: article }

= will_paginate articles

app/views/articles/new.html.haml
%h2= t 'article.new.title'
= render 'form'

app/views/articles/show.html.haml
= render article