config/routes.rb
AnifagDb::Application.routes.draw do    

  devise_for :users

  root to: "static_pages#home"

  get '/search' => 'static_pages#search', as: :search

  resources :articles, except: :index
  get 'articles(/pages/:page)' => 'articles#index', as: :articles
  get 'tags/:tag(/pages/:page)' => 'tags#show', as: :tagged_with

  get 'categories/:id(/pages/:page)' => 'categories#show', as: :category

  namespace :users do
    get '/:id' => 'users#show', as: :user
  end

  mount Rich::Engine => '/rich', :as => 'rich'

end

app/views/layouts/_footer.html.erb
<footer class="container" id="footer">
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span4">
          <small>
            Anifag DB
            <!--[if lte IE 8]>
              <span style='filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=2); display: inline-block;''>
            <![endif]-->
            <span style='-webkit-transform: rotate(180deg); 
                         -moz-transform: rotate(180deg); 
                         -o-transform: rotate(180deg); 
                         -khtml-transform: rotate(180deg); 
                         -ms-transform: rotate(180deg); 
                         transform: rotate(180deg); 
                         display: inline-block;'>
              &copy;
            </span>
            <!--[if lte IE 8]></span><![endif]-->
            <%= Time.current.year %>
          </small>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_google-analytics.html.erb
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src='//www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top'>
  <div class='navbar-inner'>
    <div class='container'>
      <%= link_to 'AnifagDB', root_path, class: 'brand' %>
      <ul class="nav" id="head-menu">
        <li><%= link_to t('home'), root_path %></li>
        <li><%= link_to t('articles'), articles_path %></li>        
      </ul>
      <div class='nav-collapse collapse pull-right'>
        <ul class="nav">
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, users_user_path(current_user) %></li>
            <li><%= link_to t('logout'), destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to t('enter'), new_user_session_path %></li>
          <%end %>
        </ul>      
        <%= form_tag search_path, method: :get, class: 'navbar-search' do %>
          <%= search_field_tag :query, params[:query], class: 'search-query', placeholder: t('form.search.search_text') %>
        <% end %>
      </div>
    </div>
  </div>
</header>
<div class='container', id='header'>
  <%= image_tag 'rails.png', class: "header-image" %>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <p class="alert alert-info"><%= notice %></p>
<% elsif alert %>
  <p class="alert alert-error"><%= alert %></p>
<% elsif flash[:error] %>
  <div class="alert alert-error">
    <%= flash[:error] %>
    <% if @errors %>
      <ul>
        <% @errors.each do |msg| %>
          <li><%= msg %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>
<% elsif flash[:success] %>
  <p class="alert alert-success"><%= flash[:success] %></p>
<% end %>

app/views/layouts/_meta-ie.html.erb
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

app/views/layouts/_sidebar.html.haml
.sample-title
  .header
    %h4=t 'sidebar.sample_title.title'   
  .body
    .title-header
      %div{ class: "label label-info pull-right" }= link_to 'Animu', '#', class: "title-type"
      %h4.title-name= link_to 'Title name', '#'
    .title-body
      .title-poster= image_tag 'rails.png', class: "img-rounded"
      .title-date
        %strong Дата выхода:
        = (Time.now - 2.years).strftime("%Y-%m-%d") 
      .title-genre 
        %strong Жанр:
        Genru
      .title-desciption 
        %strong Описание:
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec adipiscing nibh et justo euismod pulvinar et id magna. Praesent vehicula libero venenatis nisi condimentum cursus. Nulla convallis, velit...
    .title-footer= link_to 'Полное описание', '#'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/meta-ie' %>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AnifagDb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script>
    videojs.options.flash.swf = "/assets/vendor/video-js/video-js.swf"
  </script>
</head>
<body class='<%= controller.controller_name %>'>
  <!--[if lt IE 7]>
    <%= t('old_ie').html_safe %>
  <![endif]-->
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div class="span4 sidebar"><%= render 'layouts/sidebar' %></div>
      <div class="span8">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>    
  </div>
  <%= render 'layouts/footer' %>
  <%= render 'layouts/google-analytics' %>
</body>
</html>